#include "core/Localization.hpp"

namespace fnwf {

auto Localization::ensure_initialized() -> void {
    if (s_initialized)
        return;
    s_initialized = true;

    s_translations["pt"] = {
        {"options", "OPÇÕES"},
        {"resolution", "Resolução"},
        {"fullscreen", "Tela Cheia"},
        {"language", "Idioma"},
        {"show_fps", "Mostrar FPS"},
        {"vsync", "Sincronia (VSync)"},
        {"back", "Voltar"},
        {"help_input", "USE AS SETAS PARA ALTERAR"},
        {"night", "Noite"},
        {"custom_night", "Noite Custom"},
        {"oxygen", "OXIGÊNIO"},
        {"new_game", "NOVO JOGO"},
        {"continue", "CONTINUAR"},
        {"extras", "EXTRAS"},
        {"achievements", "CONQUISTAS"},
        {"quit", "SAIR"},
        {"more", "Mais..."},
        {"arcade", "ARCADE"},
        {"arcade_time", "TEMPO"},
        {"arcade_level", "NÍVEL"},
        {"door_open", "ABRIR"},
        {"door_close", "FECHAR"},
        {"light", "LUZ"},
        {"door_left", "PORTA E"},
        {"door_right", "PORTA D"},
        {"vent_light", "VENTO"},
        {"master_volume", "Volume Geral"},
        {"sfx_volume", "Efeitos Sonoros"},
        {"music_volume", "Música"},
        {"night_1_ach_title", "Pela Primeira Vez"},
        {"night_1_ach_desc", "Sobreviva à primeira noite."},
        {"night_5_ach_title", "Mestre da Mafia"},
        {"night_5_ach_desc", "Sobreviva às 5 noites principais."},
        {"night_6_ach_title", "Sem Saída"},
        {"night_6_ach_desc", "Sobreviva à brutal Noite 6."},
        {"night_7_ach_title", "Cérebro de Aço"},
        {"night_7_ach_desc", "Vença o modo 20/20/20."},
        {"new_ach_unlocked", "Nova Conquista!"},
        {"back_to_menu", "VOLTAR AO MENU"},
        {"news_title", "MÁFIA HQ — DIÁRIO"},
        {"news_headline_1", "SEGURANÇA"},
        {"news_headline_2", "DESAPARECIDO"},
        {"news_body_1", "As autoridades locais investigam o"},
        {"news_body_2", "desaparecimento de um segurança"},
        {"news_body_3", "na sede da Máfia dos Tabacudos."},
        {"news_body_4", "O incidente ocorreu durante a %s."},
        {"news_body_5", "O estabelecimento continua em operação."},
        {"night_complete", "%s Completa!"},
        {"press_any_key", "Pressione qualquer tecla..."},
        {"press_any_key_continue", "Pressione qualquer tecla para continuar..."},
        {"pay_services", "PAGAMENTO DE SERVIÇOS"},
        {"pay_to", "PAGUE-SE POR ESTE CHEQUE A:"},
        {"pay_date", "DATA:"},
        {"pay_signed", "Assinado:"},
        {"pay_congrats_5", "PARABÉNS POR SOBREVIVER ÀS 5 NOITES!"},
        {"click_continue", "Clique para continuar"},
        {"cat_animatronics", "ANIMATRÔNICOS"},
        {"cat_credits", "CRÉDITOS"},
        {"cat_cheats", "CHEATS"},
        {"cat_achievements", "CONQUISTAS"},
        {"extras_help", "A/D - Mudar Aba  |  ESC - Voltar"},
        {"cedro_desc", "O líder da máfia. Ele observa da cortina e ataca pela esquerda."},
        {"eser_desc", "O braço direito. Rápido e atento, ele prefere a porta direita."},
        {"alice_desc", "A hacker do grupo. Ela usa os dutos de ventilação para te cercar."},
        {"cheat_energy", "Energia Infinita"},
        {"cheat_fast", "Noites Rápidas (2x)"},
        {"on", "LIGADO"},
        {"off", "DESLIGADO"},
        {"created_by", "Criado por:"},
        {"special_thanks", "Agradececimento especial:"},
        {"warning_title", "AVISO"},
        {"warning_line1", "Este jogo contem luzes piscante, ruídos altos"},
        {"warning_line2", "e muitos jumpscares."},
        {"warning_line3", "NÃO JOGUE se você tiver epilepsia ou for sensível"},
        {"warning_line4", "a sustos repentinos."},
        {"story_skip", "Aperte ENTER para avançar"},
        {"story_start_night", "Aperte ENTER para começar a noite"},
        {"discord_server", "Máfia dos Tabacudos"},
        {"discord_channel", "# segurança"},
        {"discord_input", "Mensagem #segurança"},
        {"chan_general", "# geral"},
        {"chan_announcements", "# avisos"},
        {"chan_security", "# segurança"},
        {"chan_cameras", "# câmeras"},
        {"power_left", "Energia restante: %d%%"},
        {"usage", "Uso:"},
        {"am", "AM"},
        {"fps_counter", "FPS: %d"},
        {"discord_rpc", "Discord RPC"},
        {"quality", "Qualidade"},
        {"high", "Alta"},
        {"low", "Baixa"},
        {"ready", "PRONTO"},
        {"custom_controls_help", "W/S - Ajustar AI | ENTER - Começar"},
        {"loading", "Carregando..."},
        {"tip_1", "DICA: Use a luz para verificar os corredores."},
        {"tip_2", "DICA: O Eser pode ser visto nas câmeras, mas ele é rápido."},
        {"tip_3", "DICA: Se a Alice estiver na ventilação, use a máscara."},
        {"tip_4", "DICA: Economize energia. A noite é longa."},
        {"tip_5", "DICA: A porta só gasta energia se estiver fechada."},
        {"tip_6", "DICA: O Cedro ataca pelo lado esquerdo."},
        {"tip_7", "DICA: O Sonk odeia ser observado."},
        {"tip_8", "DICA: O Eser ataca pelo lado direito."},
        {"tip_9", "DICA: Ouça atentamente os sons."},
        {"tip_10", "DICA: Sobreviva até as 6 AM."},
        {"tip_11", "CURIOSIDADE: A pizzaria foi fechada 3 vezes pela vigilância sanitária."},
        {"tip_12", "CURIOSIDADE: Dizem que o animatrônico do dev nunca dorme."},
        {"ach_title_screen", "CONQUISTAS - FIVE NIGHTS WITH FRIENDS"},
        {"ach_help", "Pressione ESC ou ESPAÇO para voltar"},
        {"renan_desc", "O herói local."},
        {"newspaper_name", "A GAZETA DOS TABACUDOS"},
        {"newspaper_h1", "PIZZARIA FECHADA!"},
        {"newspaper_h2", "ESQUEMA DE CORRUPÇÃO REVELADO"},
        {"newspaper_p1", "O ex-segurança Renan Lucas entregou hoje"},
        {"newspaper_p2", "as autoridades uma série de logs confidenciais"},
        {"newspaper_p3", "do Discord que comprovam que a Pizzaria era"},
        {"newspaper_p4", "um centro de operações clandestinas da Máfia."},
        {"newspaper_p5", "O 'Big Boss' Cedro e seus cúmplices fugiram"},
        {"newspaper_p6", "antes da chegada da polícia..."},
        {"newspaper_p7", "Renan Lucas recebeu o título de herói local."},
        {"apply_code", "APLICAR CÓDIGO"},
        {"preset_1", "BUAAA"},
        {"preset_2", "E pq vejemos"},
        {"preset_3", "Não força a barra"},
        {"preset_secret", "Não me chame de ditador"},
        {"company_name", "MÁFIA BRASILEIRA DOS TABACUDOS"},
        {"currency_us", "$"},
        {"currency_br", "R$"},
        {"vsync_restart_pt", "* Reinicie o jogo para aplicar VSync"},
        {"vsync_restart_en", "* Restart the game to apply VSync"},
        {"discord_status_menu", "No Menu"},
        {"discord_status_custom", "Configurando"},
        {"discord_status_custom_night", "Noite Customizada"},
        {"discord_status_menu_en", "In the Menu"},
        {"discord_status_custom_en", "Configuring"},
        {"discord_status_custom_night_en", "Custom Night"},
        // Story messages night 1
        {"story_n1_m0", "Fala Renan! Tranquilo?"},
        {"story_n1_m1",
         "Boy, a Máfia Brasileira dos Tabacudos tá expandindo os negócios. Abrimos a Pizzaria e "
         "precisamos de alguém de confiança."},
        {"story_n1_m2",
         "O turno é da meia-noite às seis. O pagamento é bom, mas o lugar é meio... 'ativo' demais "
         "à noite."},
        {"story_n1_m3",
         "Opa, se tá pagando bem, eu tô dentro! O que pode dar errado numa pizzaria?"},
        {"story_n1_m4",
         "Hahaha é esse o espírito! Já te dei cargo de Segurança aqui no server. Chega aí no canal "
         "#câmeras."},
        {"story_n1_m5",
         "Escuta bem: Eu e o Eser... a gente gosta de testar a segurança. Sabe como é, treinamento "
         "da Máfia."},
        {"story_n1_m6", "Se a gente sumir do palco nas câmeras, é porque estamos indo te visitar."},
        {"story_n1_m7",
         "Pera, 'visitar'? Com essas fantasias enormes? Isso tá me cheirando a pegadinha."},
        {"story_n1_m8",
         "Fica de olho nas luzes e portas. Se eu chegar na esquerda ou o Eser na direita, FECHA "
         "TUDO."},
        {"story_n1_m9",
         "Mas cuidado com a energia, o gerador da pizzaria é movido a coxinha e tá quase "
         "acabando."},
        {"story_n1_m10",
         "Ah, e a Alice... ela não gosta muito do palco. Gosta de lugares apertados, tipo os "
         "dutos."},
        {"story_n1_m11",
         "Cedro... por que as vozes de vocês parecem tão metálicas? E por que esse lugar é tão "
         "escuro?"},
        {"story_n1_m12",
         "Efeito colateral do 'business', Renanzin. Fica na sala, economiza luz e sobrevive até as "
         "6. Se vc ganhar, tem bônus no salário mínimo!"},
        {"story_n1_m13", "Salário mínimo (R$ 1621)? Agora sim virou um emprego sério. Vou nessa."},
        // Story messages night 2-7, 99...
        {"story_n2_m0", "Boa, você sobreviveu à primeira noite."},
        {"story_n2_m1", "Não vou mentir, quase infartei umas cinco vezes."},
        {"story_n2_m2", "Hoje a gente vai pressionar mais. Eser já está aquecendo os circuitos."},
        {"story_n2_m3", "Se ele vier rápido assim, eu vou ficar sem energia em meia hora."},
        {"story_n2_m4", "Usa as câmeras com calma. Porta só quando for certeza."},
        {"story_n2_m5", "E presta atenção nos passos. Eles entregam quem está perto."},
        {"story_n3_m0", "Noite 3. Agora o Sonk entrou no jogo."},
        {"story_n3_m1", "Mais um? Esse lugar tá virando arena."},
        {"story_n3_m2", "Ele começa no Pirate Cove e corre para a porta esquerda."},
        {"story_n3_m3", "Então tenho que olhar a câmera dele com frequência."},
        {"story_n3_m4", "Isso. Se você ignorar por muito tempo, ele dispara sem aviso."},
        {"story_n3_m5", "Maravilha. Vou sobreviver no puro reflexo."},
        {"story_n4_m0", "Você tá indo longe demais, segurança."},
        {"story_n4_m1", "E vocês continuam tentando me derrubar toda noite."},
        {"story_n4_m2", "Na Noite 4, Alice vai aparecer mais nos dutos."},
        {"story_n4_m3", "Se eu ouvir ruído de ventilação, já sei que ela está perto."},
        {"story_n4_m4", "Isso. E não esquece: sem energia, sem defesa."},
        {"story_n4_m5", "Entendi. Gestão de energia e sangue frio."},
        {"story_n5_m0", "Chegamos na Noite 5. A principal."},
        {"story_n5_m1", "Se eu passar hoje, acabou meu contrato com vocês?"},
        {"story_n5_m2", "Acabou... em teoria."},
        {"story_n5_m3", "Resposta suspeita demais pro meu gosto."},
        {"story_n5_m4", "Só segura até 6AM e pega seu cheque."},
        {"story_n5_m5", "Fechado. Hoje ninguém me tira dessa sala."},
        {"story_n6_m0", "Renan... você ainda está aqui?"},
        {"story_n6_m1",
         "O salário caiu na conta, Cedro. Mas eu vi coisas que não devia ter visto naquelas "
         "câmeras."},
        {"story_n6_m2",
         "Você é curioso, né? A Máfia não gosta de curiosos. Mas se você quer tanto saber o que "
         "acontece na Noite 6..."},
        {"story_n6_m3",
         "Esteja avisado: o Eser e a Alice não vão mais brincar. Eles estão furiosos."},
        {"story_n6_m4", "Eu já entendi o jogo de vocês. Eu aceito o desafio. Vamos terminar isso."},
        {"story_n6_m5",
         "Então sobreviva. Se conseguir, talvez você descubra a verdade sobre a Pizzaria da "
         "Máfia."},
        {"story_n7_m0", "Então você quer brincar de Noite Custom?"},
        {"story_n7_m1", "Quero encerrar isso no modo mais difícil."},
        {"story_n7_m2", "Digita o código certo e você vai ver o inferno da pizzaria."},
        {"story_n7_m3", "Cedro, Eser, Alice e Sonk sem piedade. Sem rota segura."},
        {"story_n7_m4", "Perfeito. Eu também não vou ter piedade."},
        {"story_n7_m5", "Então entra e prova que aguenta até 6AM."},
        // Night transition messages
        {"transition_n2_m0", "Eai mano! Sobreviveu! Parabéns pela primeira noite!"},
        {"transition_n2_m1", "Mas não relaxa não... a Noite 2 é mais agitada."},
        {"transition_n2_m2", "Eu e o Eser vamos nos mover mais rápido agora."},
        {"transition_n2_m3", "Mais rápido?? Já tava difícil!"},
        {"transition_n2_m4", "Relaxa, você já sabe o esquema. Câmeras, portas, luzes."},
        {"transition_n2_m5", "Só não gasta energia à toa. Boa sorte!"},
        {"transition_n3_m0", "Duas noites! Tá ficando bom nisso hein!"},
        {"transition_n3_m1", "A Noite 3 é onde começa a ficar sério de verdade."},
        {"transition_n3_m2", "A gente vai ficar bem mais agressivo agora..."},
        {"transition_n3_m3", "Vocês tão fazendo isso de propósito né?"},
        {"transition_n3_m4", "Hehehe... talvez. Fica esperto com os dois lados!"},
    };

    s_translations["en"] = {
        {"options", "OPTIONS"},
        {"resolution", "Resolution"},
        {"fullscreen", "Fullscreen"},
        {"language", "Language"},
        {"show_fps", "Show FPS"},
        {"vsync", "VSync"},
        {"back", "Back"},
        {"help_input", "USE ARROW KEYS TO NAVIGATE"},
        {"night", "Night"},
        {"custom_night", "Custom Night"},
        {"oxygen", "OXYGEN"},
        {"new_game", "NEW GAME"},
        {"continue", "CONTINUE"},
        {"extras", "EXTRAS"},
        {"achievements", "ACHIEVEMENTS"},
        {"quit", "QUIT"},
        {"more", "More..."},
        {"arcade", "ARCADE"},
        {"arcade_time", "TIME"},
        {"arcade_level", "LEVEL"},
        {"door_open", "OPEN"},
        {"door_close", "CLOSE"},
        {"light", "LIGHT"},
        {"door_left", "DOOR L"},
        {"door_right", "DOOR R"},
        {"vent_light", "VENT"},
        {"master_volume", "Master Volume"},
        {"sfx_volume", "Sound Effects"},
        {"music_volume", "Music"},
        {"night_1_ach_title", "The First Step"},
        {"night_1_ach_desc", "Survive the first night of the job."},
        {"night_5_ach_title", "Mafia Master"},
        {"night_5_ach_desc", "Complete the initial 5-night contract."},
        {"night_6_ach_title", "Overtime"},
        {"night_6_ach_desc", "Survive the brutal Night 6."},
        {"night_7_ach_title", "Absolute Legend"},
        {"night_7_ach_desc", "Survive the 20/20/20 challenge."},
        {"new_ach_unlocked", "Achievement Unlocked!"},
        {"back_to_menu", "BACK TO MENU"},
        {"news_title", "MAFIA HQ NEWS — DAILY EDITION"},
        {"news_headline_1", "LOCAL SECURITY"},
        {"news_headline_2", "REPORTED MISSING"},
        {"news_body_1", "Authorities are now investigating the"},
        {"news_body_2", "disappearance of a night shift guard"},
        {"news_body_3", "at the Mafia of Tabacudos HQ."},
        {"news_body_4", "The event occurred during %s."},
        {"news_body_5", "Business operations continue as normal."},
        {"night_complete", "NIGHT %s COMPLETE"},
        {"press_any_key", "Press any key..."},
        {"press_any_key_continue", "Press any key to continue..."},
        {"pay_services", "SERVICE PAYMENT ADVICE"},
        {"pay_to", "PAY TO THE ORDER OF:"},
        {"pay_date", "DATE:"},
        {"pay_signed", "Signed:"},
        {"pay_congrats_5", "CONGRATULATIONS ON FINISHING YOUR CONTRACT!"},
        {"click_continue", "Click to continue"},
        {"cat_animatronics", "ANIMATRONICS"},
        {"cat_credits", "CREDITS"},
        {"cat_cheats", "MODIFIERS"},
        {"cat_achievements", "ACHIEVEMENTS"},
        {"extras_help", "A/D - Panels  |  ESC - Back"},
        {"cedro_desc", "The Mafia Boss. Watches from the curtains and strikes from the left hall."},
        {"eser_desc", "The enforcer. Extremely fast and aggressive on the right hall."},
        {"alice_desc", "Technical specialist. Uses the vents to bypass your defenses."},
        {"cheat_energy", "Infinite Energy"},
        {"cheat_fast", "Fast Nights (2x)"},
        {"on", "ENABLED"},
        {"off", "DISABLED"},
        {"created_by", "Created by:"},
        {"special_thanks", "Special thanks:"},
        {"warning_title", "WARNING"},
        {"warning_line1", "This game contains flashing lights, loud noises"},
        {"warning_line2", "and many jumpscares."},
        {"warning_line3", "DO NOT PLAY if you have epilepsy or are sensitive"},
        {"warning_line4", "to sudden frights."},
        {"story_skip", "Press ENTER to advance"},
        {"story_start_night", "Press ENTER to start the night"},
        {"discord_server", "Mafia of Tabacudos"},
        {"discord_channel", "# security"},
        {"discord_input", "Message #security"},
        {"chan_general", "# general"},
        {"chan_announcements", "# announcements"},
        {"chan_security", "# security"},
        {"chan_cameras", "# cameras"},
        {"power_left", "Power Left: %d%%"},
        {"usage", "Usage:"},
        {"am", "AM"},
        {"fps_counter", "FPS: %d"},
        {"discord_rpc", "Discord RPC"},
        {"quality", "Quality"},
        {"high", "High"},
        {"low", "Low"},
        {"ready", "READY"},
        {"custom_controls_help", "W/S - Adjust AI | ENTER - Start"},
        {"loading", "Loading..."},
        {"tip_1", "TIP: Use the light to check the hallways."},
        {"tip_2", "TIP: Eser can be seen on cameras, but he's fast."},
        {"tip_3", "TIP: If Alice is in the vents, use the mask."},
        {"tip_4", "TIP: Save power. The night is long."},
        {"tip_5", "TIP: Doors only drain power when closed."},
        {"tip_6", "TIP: Cedro attacks from the left side."},
        {"tip_7", "TIP: Sonk hates being watched."},
        {"tip_8", "TIP: Eser attacks from the right side."},
        {"tip_9", "TIP: Listen carefully to the sounds."},
        {"tip_10", "TIP: Survive until 6 AM."},
        {"tip_11", "FUN FACT: The pizzeria was shut down 3 times by health inspection."},
        {"tip_12", "FUN FACT: They say the dev's animatronic never sleeps."},
        {"ach_title_screen", "ACHIEVEMENTS - FIVE NIGHTS WITH FRIENDS"},
        {"ach_help", "Press ESC or SPACE to go back"},
        {"renan_desc", "The local hero."},
        {"newspaper_name", "THE TABACUDOS GAZETTE"},
        {"newspaper_h1", "PIZZERIA SHUT DOWN!"},
        {"newspaper_h2", "CORRUPTION SCHEME EXPOSED"},
        {"newspaper_p1", "Former security guard Renan Lucas turned in"},
        {"newspaper_p2", "to authorities a series of confidential logs"},
        {"newspaper_p3", "from Discord proving the Pizzeria was"},
        {"newspaper_p4", "a center of clandestine Mafia operations."},
        {"newspaper_p5", "The 'Big Boss' Cedro and his accomplices fled"},
        {"newspaper_p6", "before the police arrived..."},
        {"newspaper_p7", "Renan Lucas received the title of local hero."},
        {"apply_code", "APPLY CODE"},
        {"preset_1", "BUAAA"},
        {"preset_2", "E pq vejemos"},
        {"preset_3", "Don't push it"},
        {"preset_secret", "Don't call me a dictator"},
        {"company_name", "MAFIA OF TABACUDOS BRAZIL"},
        {"currency_us", "$"},
        {"currency_br", "R$"},
        {"vsync_restart_pt", "* Reinicie o jogo para aplicar VSync"},
        {"vsync_restart_en", "* Restart the game to apply VSync"},
        {"discord_status_menu", "No Menu"},
        {"discord_status_custom", "Configurando"},
        {"discord_status_custom_night", "Noite Customizada"},
        {"discord_status_menu_en", "In the Menu"},
        {"discord_status_custom_en", "Configuring"},
        {"discord_status_custom_night_en", "Custom Night"},
        {"story_n1_m0", "Hey Renan! How's it going?"},
        {"story_n1_m1",
         "Boy, the Mafia of Tabacudos is expanding. We opened the Pizza place and need someone we "
         "can trust."},
        {"story_n1_m2",
         "The shift is midnight to six. Pay is good, but the place is a bit... 'active' at night."},
        {"story_n1_m3", "Oh, if it pays well, I'm in! What could go wrong at a pizzeria?"},
        {"story_n1_m4",
         "Hahaha that's the spirit! I gave you the Security role here in the server. Join the "
         "#cameras channel."},
        {"story_n1_m5",
         "Listen carefully: Máfia and I... we like to test security. You know, Mafia training."},
        {"story_n1_m6",
         "If we vanish from the stage on the cameras, it's because we're coming to visit."},
        {"story_n1_m7", "Wait, 'visit'? In those huge suits? This smells like a prank."},
        {"story_n1_m8",
         "Keep an eye on the lights and doors. If I come from the left or Eser from the right, "
         "CLOSE EVERYTHING."},
        {"story_n1_m9",
         "But watch the power, the pizzeria's generator is powered by snacks and it's almost out."},
        {"story_n1_m10",
         "Oh, and Alice... she doesn't like the stage much. She likes tight spaces, like the "
         "vents."},
        {"story_n1_m11",
         "Cedro... why do your voices sound so metallic? And why is this place so dark?"},
        {"story_n1_m12",
         "Side effect of 'business', Renanzin. Stay in the room, save light, and survive until 6. "
         "If you win, there's a bonus!"},
        {"story_n1_m13", "Minimum wage? Now it's a serious job. I'm in."},
        {"story_n2_m0", "Nice, you survived the first night."},
        {"story_n2_m1", "Not gonna lie, I almost had five heart attacks."},
        {"story_n2_m2", "Tonight we push harder. Eser is already warming up his circuits."},
        {"story_n2_m3", "If he moves that fast, I'll run out of power in half an hour."},
        {"story_n2_m4", "Use cameras calmly. Door only when you are sure."},
        {"story_n2_m5", "And pay attention to footsteps. They reveal who is close."},
        {"story_n3_m0", "Night 3. Sonk is now in the game."},
        {"story_n3_m1", "Another one? This place is becoming an arena."},
        {"story_n3_m2", "He starts at Pirate Cove and sprints to the left door."},
        {"story_n3_m3", "So I need to check his camera often."},
        {"story_n3_m4", "Exactly. Ignore him for too long and he runs with no warning."},
        {"story_n3_m5", "Great. I'll survive on pure reflex."},
        {"story_n4_m0", "You're going too far, security guard."},
        {"story_n4_m1", "And you keep trying to take me down every night."},
        {"story_n4_m2", "On Night 4, Alice will pressure the vents harder."},
        {"story_n4_m3", "If I hear vent noise, I know she's close."},
        {"story_n4_m4", "Right. And remember: no power, no defense."},
        {"story_n4_m5", "Understood. Power management and cold blood."},
        {"story_n5_m0", "We reached Night 5. The main one."},
        {"story_n5_m1", "If I pass tonight, does my contract end?"},
        {"story_n5_m2", "It ends... in theory."},
        {"story_n5_m3", "That's way too suspicious for my taste."},
        {"story_n5_m4", "Just hold until 6AM and take your paycheck."},
        {"story_n5_m5", "Deal. Tonight no one takes me out of that office."},
        {"story_n6_m0", "Renan... are you still here?"},
        {"story_n6_m1",
         "The salary hit the account, Cedro. But I saw things I wasn't supposed to see on those "
         "cameras."},
        {"story_n6_m2",
         "You're curious, right? The Mafia doesn't like curious people. But if you want to know "
         "what happens on Night 6..."},
        {"story_n6_m3", "Be warned: Eser and Alice aren't playing anymore. They are furious."},
        {"story_n6_m4",
         "I already understand your game. I accept the challenge. Let's finish this."},
        {"story_n6_m5",
         "Then survive. If you do, maybe you'll discover the truth about the Mafia Pizzeria."},
        {"story_n7_m0", "So you want to play Custom Night?"},
        {"story_n7_m1", "I want to end this on the hardest mode."},
        {"story_n7_m2", "Type the right code and you'll see this place's hell mode."},
        {"story_n7_m3", "Cedro, Eser, Alice and Sonk with no mercy. No safe route."},
        {"story_n7_m4", "Perfect. I won't show mercy either."},
        {"story_n7_m5", "Then get in and prove you can hold until 6AM."},
        // Night transition messages
        {"transition_n2_m0", "Hey bro! You survived! Congrats on the first night!"},
        {"transition_n2_m1", "But don't relax... Night 2 is more intense."},
        {"transition_n2_m2", "Me and Eser are gonna move faster now."},
        {"transition_n2_m3", "Faster?? It was already hard enough!"},
        {"transition_n2_m4", "Chill, you already know the deal. Cameras, doors, lights."},
        {"transition_n2_m5", "Just don't waste power. Good luck!"},
        {"transition_n3_m0", "Two nights! You're getting good at this!"},
        {"transition_n3_m1", "Night 3 is where it gets really serious."},
        {"transition_n3_m2", "We're going to be much more aggressive now..."},
        {"transition_n3_m3", "Are you guys doing this on purpose?"},
        {"transition_n3_m4", "Hehehe... maybe. Stay sharp on both sides!"},
    };
}

auto Localization::set_language(const std::string& lang) -> void {
    ensure_initialized();
    if (s_translations.count(lang)) {
        s_current_lang = lang;
    }
}

auto Localization::get_language() -> const std::string& {
    return s_current_lang;
}

auto Localization::get_text(const std::string& key) -> const std::string& {
    ensure_initialized();
    auto& lang_map = s_translations[s_current_lang];
    auto it = lang_map.find(key);
    if (it != lang_map.end()) {
        return it->second;
    }
    return key;
}

}  // namespace fnwf
