#!/usr/bin/env python3
"""Generate crates/core/src/localization/localization_data.rs from the C++ Localization.cpp."""
import re
import sys

SRC = "/home/renan/Projetos/cpp/fnwf/src/core/Localization.cpp"
OUT = "/home/renan/Projetos/rust/fnwf/crates/core/src/localization/localization_data.rs"


def extract_block(text, lang):
    marker = f's_translations["{lang}"] = {{'
    start = text.index(marker) + len(marker)
    depth = 1
    i = start
    in_str = False
    esc = False
    while i < len(text):
        ch = text[i]
        if in_str:
            if esc:
                esc = False
            elif ch == "\\":
                esc = True
            elif ch == '"':
                in_str = False
        else:
            if ch == '"':
                in_str = True
            elif ch == "{":
                depth += 1
            elif ch == "}":
                depth -= 1
                if depth == 0:
                    return text[start:i]
        i += 1
    raise ValueError("unterminated block")


def unescape_cpp(s):
    out = []
    i = 0
    while i < len(s):
        ch = s[i]
        if ch == "\\" and i + 1 < len(s):
            nxt = s[i + 1]
            mapping = {"n": "\n", "t": "\t", "r": "\r", "\\": "\\", '"': '"', "0": "\0"}
            out.append(mapping.get(nxt, nxt))
            i += 2
        else:
            out.append(ch)
            i += 1
    return "".join(out)


ENTRY = re.compile(
    r'\{\s*"((?:[^"\\]|\\.)*)"\s*,\s*((?:"(?:[^"\\]|\\.)*"\s*)+)\}',
    re.DOTALL,
)
STRING = re.compile(r'"((?:[^"\\]|\\.)*)"', re.DOTALL)


def parse_entries(block):
    entries = []
    for m in ENTRY.finditer(block):
        key = unescape_cpp(m.group(1))
        parts = [unescape_cpp(s) for s in STRING.findall(m.group(2))]
        value = "".join(parts)
        entries.append((key, value))
    return entries


def rust_lit(s):
    out = s.replace("\\", "\\\\").replace('"', '\\"')
    out = out.replace("\n", "\\n").replace("\t", "\\t").replace("\r", "\\r")
    return '"' + out + '"'


def emit(name, entries):
    lines = [f"pub static {name}: &[(&str, &str)] = &["]
    for k, v in entries:
        lines.append(f"    ({rust_lit(k)}, {rust_lit(v)}),")
    lines.append("];")
    return "\n".join(lines)


def main():
    with open(SRC, encoding="utf-8") as f:
        text = f.read()
    pt = parse_entries(extract_block(text, "pt"))
    en = parse_entries(extract_block(text, "en"))
    body = "\n".join(
        [
            "// @generated by scripts/gen_localization.py — do not edit by hand.",
            "// Source: src/core/Localization.cpp (GPL-3.0).",
            "",
            emit("PT", pt),
            "",
            emit("EN", en),
            "",
        ]
    )
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(body)
    print(f"pt={len(pt)} en={len(en)} -> {OUT}")


if __name__ == "__main__":
    sys.exit(main())
